services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
  news-server:
    ports:
      - "8080:8080"
    depends_on:
      - redis
    build: news-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  news-client:
    ports:
      - "8000:8000"
    depends_on:
      - news-server
    build: news-client
    environment:
      - VITE_NEWS_SERVER_PORT=8080
